/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Book: typeof import('./src/components/icon/Book.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    Dev: typeof import('./src/components/icon/Dev.vue')['default']
    IconBook: typeof import('./src/components/icon/IconBook.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    IconDev: typeof import('./src/components/icon/IconDev.vue')['default']
    IconEye: typeof import('./src/components/icon/IconEye.vue')['default']
    IconEyeClose: typeof import('./src/components/icon/IconEyeClose.vue')['default']
    IconFilterOutline: typeof import('./src/components/icon/IconFilterOutline.vue')['default']
    IconHorizontal: typeof import('./src/components/icon/IconHorizontal.vue')['default']
    IconImage: typeof import('./src/components/icon/IconImage.vue')['default']
    IconImagePlus: typeof import('./src/components/icon/IconImagePlus.vue')['default']
    IconList: typeof import('./src/components/icon/IconList.vue')['default']
    IconModule: typeof import('./src/components/icon/IconModule.vue')['default']
    IconOpacity: typeof import('./src/components/icon/IconOpacity.vue')['default']
    IconSet: typeof import('./src/components/icon/IconSet.vue')['default']
    IconTexture: typeof import('./src/components/icon/IconTexture.vue')['default']
    IconUpload: typeof import('./src/components/icon/IconUpload.vue')['default']
    IconVertical: typeof import('./src/components/icon/IconVertical.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
