/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/modules/': RouteRecordInfo<'/modules/', '/modules', Record<never, never>, Record<never, never>>,
    '/modules/components/LoadupButton': RouteRecordInfo<'/modules/components/LoadupButton', '/modules/components/LoadupButton', Record<never, never>, Record<never, never>>,
    '/modules/components/Module': RouteRecordInfo<'/modules/components/Module', '/modules/components/Module', Record<never, never>, Record<never, never>>,
    '/modules/components/PartFilter': RouteRecordInfo<'/modules/components/PartFilter', '/modules/components/PartFilter', Record<never, never>, Record<never, never>>,
    '/modules/components/StatDisplay': RouteRecordInfo<'/modules/components/StatDisplay', '/modules/components/StatDisplay', Record<never, never>, Record<never, never>>,
    '/offset-calc/': RouteRecordInfo<'/offset-calc/', '/offset-calc', Record<never, never>, Record<never, never>>,
    '/offset-calc/components/FileButton': RouteRecordInfo<'/offset-calc/components/FileButton', '/offset-calc/components/FileButton', Record<never, never>, Record<never, never>>,
    '/offset-calc/components/OpacityButton': RouteRecordInfo<'/offset-calc/components/OpacityButton', '/offset-calc/components/OpacityButton', Record<never, never>, Record<never, never>>,
    '/offset-calc/components/TexSet': RouteRecordInfo<'/offset-calc/components/TexSet', '/offset-calc/components/TexSet', Record<never, never>, Record<never, never>>,
    '/offset-calc/components/TextureCanvas': RouteRecordInfo<'/offset-calc/components/TextureCanvas', '/offset-calc/components/TextureCanvas', Record<never, never>, Record<never, never>>,
    '/offset-calc/components/ToggleButton': RouteRecordInfo<'/offset-calc/components/ToggleButton', '/offset-calc/components/ToggleButton', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/guide/index.vue': {
      routes: '/guide/'
      views: never
    }
    'src/pages/modules/index.vue': {
      routes: '/modules/'
      views: never
    }
    'src/pages/modules/components/LoadupButton.vue': {
      routes: '/modules/components/LoadupButton'
      views: never
    }
    'src/pages/modules/components/Module.vue': {
      routes: '/modules/components/Module'
      views: never
    }
    'src/pages/modules/components/PartFilter.vue': {
      routes: '/modules/components/PartFilter'
      views: never
    }
    'src/pages/modules/components/StatDisplay.vue': {
      routes: '/modules/components/StatDisplay'
      views: never
    }
    'src/pages/offset-calc/index.vue': {
      routes: '/offset-calc/'
      views: never
    }
    'src/pages/offset-calc/components/FileButton.vue': {
      routes: '/offset-calc/components/FileButton'
      views: never
    }
    'src/pages/offset-calc/components/OpacityButton.vue': {
      routes: '/offset-calc/components/OpacityButton'
      views: never
    }
    'src/pages/offset-calc/components/TexSet.vue': {
      routes: '/offset-calc/components/TexSet'
      views: never
    }
    'src/pages/offset-calc/components/TextureCanvas.vue': {
      routes: '/offset-calc/components/TextureCanvas'
      views: never
    }
    'src/pages/offset-calc/components/ToggleButton.vue': {
      routes: '/offset-calc/components/ToggleButton'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
